# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98ab1659b731382d223e452c96869ffbeaa7301dc62b2d57ecd9dfae4c5a92599a19268c3f90d43efb1969ef9e817449cebcc43c65a6ee3bd45a458a146e083c

test:
  secret_key_base: ef8d3611630313467cbdd2a6372dcdd5ce60b1da8fcf9848c4b76d6189e1eefa725ade8a6b9cd303328aa5dc28cc6757505b765ad91b9579ea9e37e25c3140a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
